name: "terraform infra deploy"
on: workflow_dispatch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
        
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false
          
      - name: Terraform Validate
        id: validate
        run: terraform validate
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out infra.plan
        continue-on-error: true

      