name: terraform infra deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write # Required for requesting the OIDC JWT token
  contents: read  # Required for actions/checkout

env:
  # 1. Define the cache directory globally
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs: 
  plan:
    runs-on: ubuntu-latest
    environment: plan
    outputs:
      tf_exitcode: ${{ steps.tf-plan.outputs.exit_code }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.16.4
      
      - name: create plugin cache directory
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: cache terraform providers
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-plugins-

      - name: Terraform Init
        run: terraform init -input=false
      
      - name: Terraform Validate
        run: terraform validate
          
      - name: Terraform Plan
        id: tf-plan
        run: |
          terraform plan -input=false -out infra.plan -detailed-exitcode || exitcode=$?
          exitcode=${exitcode:-0}
          echo "exit_code=$exitcode" >> $GITHUB_OUTPUT
          
          if [ $exitcode -eq 1 ]; then
            echo "Terraform plan failed!"
            exit 1
          fi

      - name: upload the plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: infra.plan

  apply:
    needs: plan
    if: needs.plan.outputs.tf_exitcode == '2'
    runs-on: ubuntu-latest
    environment: apply
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.16.4

      - name: Create Terraform Plugin Cache Dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-plugins-
          
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve infra.plan